/**
 * Spend categorisation rule table.
 *
 * Everything in this file is DATA, not logic — the matcher lives in
 * `categorise.ts`. Rules are evaluated top-to-bottom and the FIRST match wins,
 * so put specific rules (e.g. "UBER EATS" -> eating_out) above general ones
 * (e.g. "UBER" -> transport_fuel). To add coverage, append keywords to an
 * existing rule or insert a new rule at the right precedence; no code change
 * is needed. See docs/spend-categorisation.md for the full precedence order.
 */

export const CATEGORIES = [
  "groceries",
  "eating_out",
  "transport_fuel",
  "utilities",
  "rent_housing",
  "insurance",
  "loans",
  "subscriptions",
  "telecom",
  "health",
  "shopping",
  "entertainment",
  "fees_interest",
  "transfers",
  "income",
  "cash",
  "other",
] as const;

export type Category = (typeof CATEGORIES)[number];

/** Human-readable labels used by the UI and the summary query. */
export const CATEGORY_LABELS: Record<Category, string> = {
  groceries: "Groceries",
  eating_out: "Eating out & takeaways",
  transport_fuel: "Transport & fuel",
  utilities: "Utilities",
  rent_housing: "Rent & housing",
  insurance: "Insurance & medical aid",
  loans: "Loans & credit",
  subscriptions: "Subscriptions & memberships",
  telecom: "Phone & internet",
  health: "Health & pharmacy",
  shopping: "Shopping",
  entertainment: "Entertainment",
  fees_interest: "Bank fees & interest",
  transfers: "Transfers & EFTs",
  income: "Income",
  cash: "Cash withdrawals",
  other: "Other / uncategorised",
};

export function isCategory(value: string | null | undefined): value is Category {
  return typeof value === "string" && (CATEGORIES as readonly string[]).includes(value);
}

export type KeywordRule = {
  category: Category;
  /**
   * Whole-word phrases matched against the normalised (uppercased, punctuation
   * stripped) description + merchant name. A phrase can contain spaces.
   */
  keywords: string[];
  /** Only apply when the transaction is a credit/debit. Default: either. */
  direction?: "credit" | "debit";
  /** Confidence to report on a match (0..1). Default 0.85. */
  confidence?: number;
};

/**
 * Investec `transactionType` values that are authoritative on their own —
 * these win over any keyword. Everything else in `transactionType` is only
 * used as a *fallback* (see SOFT_TRANSACTION_TYPE_RULES).
 */
export const HARD_TRANSACTION_TYPE_RULES: Record<string, { category: Category; confidence: number }> = {
  FeesAndInterest: { category: "fees_interest", confidence: 0.95 },
  ATMWithdrawals: { category: "cash", confidence: 0.95 },
};

/**
 * Fallbacks used only when no keyword or MCC rule matched. Confidence is
 * deliberately low: these say "probably", not "definitely".
 */
export const SOFT_TRANSACTION_TYPE_RULES: Record<
  string,
  { category: Category; confidence: number; reason: string }
> = {
  Deposits: { category: "income", confidence: 0.6, reason: "Investec type Deposits (credit with no recognised source)" },
  OnlineBankingPayments: {
    category: "transfers",
    confidence: 0.5,
    reason: "Investec type OnlineBankingPayments to an unrecognised beneficiary",
  },
  FasterPay: { category: "transfers", confidence: 0.5, reason: "Investec type FasterPay to an unrecognised beneficiary" },
  VASTransactions: {
    category: "telecom",
    confidence: 0.5,
    reason: "Investec type VASTransactions (prepaid airtime/data/electricity) — assumed airtime",
  },
};

/**
 * Ordered keyword rules. First match wins. Mostly South African merchants,
 * plus generic words (PHARMACY, FUEL, RENT ...) so unknown merchants still
 * land somewhere sensible when their description is descriptive.
 */
export const KEYWORD_RULES: KeywordRule[] = [
  // --- Income (credits only; a debit that says "SALARY" is you paying someone) ---
  {
    category: "income",
    direction: "credit",
    confidence: 0.9,
    keywords: ["SALARY", "SALARIS", "SAL", "WAGES", "PAYROLL", "BONUS", "COMMISSION", "PENSION", "SASSA", "DIVIDEND", "STIPEND"],
  },
  { category: "transfers", direction: "debit", confidence: 0.7, keywords: ["SALARY", "SALARIS", "WAGES"] },

  // --- Bank fees & interest ---
  {
    category: "fees_interest",
    confidence: 0.9,
    keywords: [
      "SERVICE FEE",
      "SERVICE CHARGE",
      "MONTHLY FEE",
      "ACCOUNT FEE",
      "ADMIN FEE",
      "CARD FEE",
      "ATM FEE",
      "SMS FEE",
      "BANK CHARGES",
      "BANK CHARGE",
      "INTEREST",
      "OVERDRAFT",
      "PENALTY",
      "COMMISSION FEE",
      "CASH DEPOSIT FEE",
      "INTL TRANSACTION FEE",
      "FOREX FEE",
    ],
  },

  // --- Subscriptions & memberships (early, so "YOUTUBE PREMIUM" beats insurance's
  //     "PREMIUM" and "AMAZON PRIME" beats shopping's "AMAZON") ---
  {
    category: "subscriptions",
    confidence: 0.9,
    keywords: [
      "NETFLIX",
      "SHOWMAX",
      "DSTV",
      "MULTICHOICE",
      "SPOTIFY",
      "APPLE MUSIC",
      "APPLE COM BILL",
      "APPLE BILL",
      "ITUNES",
      "YOUTUBE PREMIUM",
      "YOUTUBE",
      "GOOGLE ONE",
      "GOOGLE STORAGE",
      "GOOGLE PLAY",
      "AMAZON PRIME",
      "PRIME VIDEO",
      "DISNEY PLUS",
      "DISNEY+",
      "HBO",
      "DEEZER",
      "AUDIBLE",
      "MICROSOFT 365",
      "MICROSOFT",
      "ADOBE",
      "DROPBOX",
      "ICLOUD",
      "CHATGPT",
      "OPENAI",
      "ANTHROPIC",
      "GITHUB",
      "VIRGIN ACTIVE",
      "PLANET FITNESS",
      "GYM",
      "STRAVA",
      "PATREON",
      "SUBSCRIPTION*",
      "MEMBERSHIP*",
      "XBOX",
      "PLAYSTATION",
      "NINTENDO",
      "STEAMGAMES",
      "STEAM",
      "TINDER",
      "BUMBLE",
      "LINKEDIN",
      "NEWS24",
      "DAILY MAVERICK",
      "AUDIOMACK",
    ],
  },

  // --- Car hire (exception rule: must beat the generic "RENT"/"RENTAL" below) ---
  {
    category: "transport_fuel",
    confidence: 0.9,
    keywords: ["CAR RENTAL", "CAR HIRE", "RENT A CAR", "VEHICLE RENTAL", "AVIS", "HERTZ", "EUROPCAR", "THRIFTY", "BLUU CAR", "TEMPEST", "FIRST CAR RENTAL"],
  },

  // --- Rent & housing ---
  {
    category: "rent_housing",
    confidence: 0.9,
    keywords: ["RENT", "RENTAL", "HUUR", "LEVY", "LEVIES", "BODY CORPORATE", "BODY CORP", "HOA", "APARTMENT*", "PROPERTIES", "PROPERTY", "HOME LOAN*", "BOND", "MORTGAGE", "MUNICIPAL RATES", "RATES AND TAXES", "RATES & TAXES"],
  },

  // --- Insurance & medical aid ---
  {
    category: "insurance",
    confidence: 0.9,
    keywords: [
      "OUTSURANCE",
      "DISCOVERY",
      "MOMENTUM",
      "SANTAM",
      "OLD MUTUAL",
      "SANLAM",
      "LIBERTY",
      "HOLLARD",
      "MIWAY",
      "KING PRICE",
      "BUDGET INSURANCE",
      "1ST FOR WOMEN",
      "FIRST FOR WOMEN",
      "AUTO & GENERAL",
      "AUTO AND GENERAL",
      "DIALDIRECT",
      "DIAL DIRECT",
      "NAKED",
      "PINEAPPLE",
      "BONITAS",
      "MEDIHELP",
      "BESTMED",
      "FEDHEALTH",
      "GEMS",
      "MEDICAL AID",
      "MEDSCHEME",
      "INSUR*",
      "ASSURANCE",
      "PREMIUM",
      "FUNERAL",
      "AVBOB",
      "CLIENTELE",
      "METROPOLITAN",
      "ASSUPOL",
      "PPS",
      "GAP COVER",
    ],
  },

  // --- Loans & credit ---
  {
    category: "loans",
    confidence: 0.9,
    keywords: [
      "LOAN*",
      "REPAYMENT*",
      "INSTALMENT*",
      "INSTALLMENT*",
      "WESBANK",
      "MFC",
      "VEHICLE FINANCE",
      "CAR FINANCE",
      "CREDIT CARD",
      "CREDITCARD",
      "CC PAYMENT",
      "CAPITEC LOAN",
      "AFRICAN BANK",
      "FINCHOICE",
      "WONGA",
      "LIME LOANS",
      "RCS",
      "MOBICRED",
      "PAYJUSTNOW",
      "PAYFLEX",
      "NSFAS",
      "FUNDI",
      "STUDENT LOAN",
      "TOYOTA FINANCIAL",
      "VW FINANCIAL",
      "BMW FINANCIAL",
    ],
  },

  // --- Utilities (electricity, water, municipal) ---
  {
    category: "utilities",
    confidence: 0.9,
    keywords: [
      "CITY POWER",
      "ESKOM",
      "CITY OF CAPE TOWN",
      "CITY OF JOHANNESBURG",
      "CITY OF JOBURG",
      "COJ",
      "CITY OF TSHWANE",
      "ETHEKWINI",
      "EKURHULENI",
      "MUNICIPALITY",
      "MUNICIPAL",
      "ELECTRICITY",
      "PREPAID ELEC",
      "PREPAID ELECTRICITY",
      "WATER AND SANITATION",
      "WATER & SANITATION",
      "RAND WATER",
      "JOBURG WATER",
      "UTILITIES",
      "UTILITY",
      "SOLAR",
      "GAS",
    ],
  },

  // --- Phone & internet ---
  {
    category: "telecom",
    confidence: 0.9,
    keywords: [
      "VODACOM",
      "MTN",
      "CELL C",
      "CELLC",
      "TELKOM",
      "RAIN",
      "AFRIHOST",
      "WEBAFRICA",
      "WEB AFRICA",
      "AXXESS",
      "COOL IDEAS",
      "VUMATEL",
      "VUMA",
      "OPENSERVE",
      "HEROTEL",
      "MWEB",
      "SUPERSONIC",
      "AIRTIME",
      "PREPAID AIRTIME",
      "DATA BUNDLE",
      "FIBRE",
      "FIBER",
      "INTERNET",
      "ADSL",
      "LTE",
      "MOBILE DATA",
    ],
  },

  // --- Groceries ---
  {
    category: "groceries",
    confidence: 0.9,
    keywords: [
      "WOOLWORTHS",
      "WOOLIES",
      "WW",
      "CHECKERS",
      "CHECKERS SIXTY60",
      "SIXTY60",
      "PICK N PAY",
      "PICKNPAY",
      "PNP",
      "SPAR",
      "SUPERSPAR",
      "KWIKSPAR",
      "SHOPRITE",
      "USAVE",
      "BOXER",
      "FOOD LOVERS",
      "FOOD LOVER S",
      "FRUIT & VEG",
      "FRUIT AND VEG",
      "MAKRO",
      "OK FOODS",
      "OK MINIMARK",
      "CAMBRIDGE FOOD",
      "CHOPPIES",
      "SUPERMARKET",
      "GROCER*",
      "BUTCHERY",
      "FRESH PRODUCE",
      "FARM STALL",
      "MINIMARKET",
      "MINI MARKET",
      "7 ELEVEN",
      "SEVEN ELEVEN",
      "TOPS",
      "LIQUOR",
      "BOTTLE STORE",
    ],
  },

  // --- Eating out & takeaways (must precede transport so UBER EATS / BOLT FOOD win) ---
  {
    category: "eating_out",
    confidence: 0.9,
    keywords: [
      "UBER EATS",
      "UBEREATS",
      "BOLT FOOD",
      "MR D",
      "MR D FOOD",
      "MRD FOOD",
      "MR DELIVERY",
      "NANDOS",
      "NANDO S",
      "STEERS",
      "KFC",
      "MCDONALDS",
      "MCDONALD S",
      "MCD",
      "BURGER KING",
      "WIMPY",
      "SPUR",
      "DEBONAIRS",
      "ROMANS PIZZA",
      "ROMAN S PIZZA",
      "PIZZA",
      "DOMINOS",
      "FISHAWAYS",
      "CHICKEN LICKEN",
      "OCEAN BASKET",
      "MUGG & BEAN",
      "MUGG AND BEAN",
      "MUGG BEAN",
      "VIDA E CAFFE",
      "VIDA",
      "SEATTLE COFFEE",
      "STARBUCKS",
      "BOOTLEGGER",
      "KAUAI",
      "ROCOMAMAS",
      "PANAROTTIS",
      "COL CACCHIO",
      "TASHAS",
      "KREAM",
      "RESTAURANT*",
      "RESTUARANT",
      "CAFE",
      "CAFFE",
      "COFFEE",
      "BISTRO",
      "DINER",
      "GRILL",
      "BAKERY",
      "TAKEAWAY*",
      "FOOD",
      "BAR",
      "PUB",
      "TAVERN",
      "SUSHI",
      "BURGER",
      "EATERY",
      "KITCHEN",
    ],
  },

  // --- Transport & fuel ---
  {
    category: "transport_fuel",
    confidence: 0.9,
    keywords: [
      "UBER",
      "UBER TRIP",
      "BOLT",
      "BOLT EU",
      "INDRIVE",
      "INDRIVER",
      "ENGEN",
      "SHELL",
      "SASOL",
      "BP",
      "CALTEX",
      "ASTRON",
      "TOTALENERGIES",
      "TOTAL ENERGIES",
      "PUMA ENERGY",
      "FUEL",
      "PETROL",
      "DIESEL",
      "GARAGE",
      "FILLING STATION",
      "SERVICE STATION",
      "MOTORS",
      "GAUTRAIN",
      "MYCITI",
      "MY CITI",
      "METRORAIL",
      "PRASA",
      "SANRAL",
      "E TOLL",
      "ETOLL",
      "TOLL",
      "TOLL PLAZA",
      "PARKING",
      "PARKADE",
      "CAR WASH",
      "CARWASH",
      "TYRES",
      "TIGER WHEEL",
      "SUPA QUICK",
      "FLYSAFAIR",
      "SAFAIR",
      "KULULA",
      "LIFT",
      "AIRLINK",
      "SAA",
      "AIRWAYS",
      "AIRLINE",
            "TAXI",
      "LICENCE RENEWAL",
      "LICENSE RENEWAL",
      "TRAFFIC FINE",
      "AARTO",
    ],
  },

  // --- Health & pharmacy ---
  {
    category: "health",
    confidence: 0.9,
    keywords: [
      "DIS CHEM",
      "DISCHEM",
      "CLICKS",
      "PHARM*",
      "CHEMIST",
      "APTEEK",
      "MEDIRITE",
      "ALPHA PHARM",
      "LINK PHARMACY",
      "NETCARE",
      "MEDICLINIC",
      "LIFE HEALTHCARE",
      "HOSPITAL",
      "CLINIC",
      "DOCTOR",
      "DENTIST",
      "DENTAL",
      "OPTOMETRIST",
      "SPEC SAVERS",
      "SPECSAVERS",
      "TORGA",
      "PATHCARE",
      "LANCET",
      "AMPATH",
      "PHYSIO*",
      "PSYCHOLOG*",
      "THERAPIST",
      "MEDICAL",
      "VET",
      "VETERINAR*",
    ],
  },

  // --- Entertainment ---
  {
    category: "entertainment",
    confidence: 0.85,
    keywords: [
      "STER KINEKOR",
      "STERKINEKOR",
      "NU METRO",
      "NUMETRO",
      "CINEMA",
      "MOVIES",
      "THEATRE",
      "THEATER",
      "COMPUTICKET",
      "TICKETPRO",
      "WEBTICKETS",
      "QUICKET",
      "HOWLER",
      "TICKETS",
      "CONCERT",
      "FESTIVAL",
      "BOWLING",
      "ARCADE",
      "GOLD REEF",
      "GOLD REEF CITY",
      "SUN CITY",
      "SUN INTERNATIONAL",
      "MONTECASINO",
      "CASINO",
      "HOLLYWOODBETS",
      "BETWAY",
      "SPORTINGBET",
      "SUPABETS",
      "LOTTO",
      "ITHUBA",
      "PLAY",
      "GAMES",
      "MUSEUM",
      "AQUARIUM",
      "ZOO",
      "BOOKINGS COM",
      "BOOKING COM",
      "AIRBNB",
      "LEKKESLAAP",
      "SAFARINOW",
      "HOTEL",
      "LODGE",
      "RESORT",
      "SPA",
    ],
  },

  // --- Shopping ---
  {
    category: "shopping",
    confidence: 0.85,
    keywords: [
      "TAKEALOT",
      "AMAZON",
      "SHEIN",
      "TEMU",
      "ALIEXPRESS",
      "SUPERBALIST",
      "BASH",
      "ZANDO",
      "MR PRICE",
      "MRP",
      "MRPRICE",
      "EDGARS",
      "TRUWORTHS",
      "FOSCHINI",
      "TFG",
      "ACKERMANS",
      "PEP",
      "PEP STORES",
      "JET",
      "MARKHAM",
      "SPORTSCENE",
      "TOTALSPORTS",
      "SPORTSMANS WAREHOUSE",
      "SPORTSMAN S WAREHOUSE",
      "CAPE UNION MART",
      "COTTON ON",
      "H&M",
      "ZARA",
      "COUNTRY ROAD",
      "GAME",
      "GAME STORES",
      "BUILDERS",
      "BUILDERS WAREHOUSE",
      "LEROY MERLIN",
      "CASHBUILD",
      "MICA",
      "HARDWARE",
      "INCREDIBLE CONNECTION",
      "ISTORE",
      "HIFI CORP",
      "HI FI CORP",
      "APPLE STORE",
      "SAMSUNG",
      "MAKRO",
      "CORICRAFT",
      "MR PRICE HOME",
      "SHEET STREET",
      "HOME CHOICE",
      "HOMECHOICE",
      "WEYLANDTS",
      "HOUSE & HOME",
      "HOUSE AND HOME",
      "TOYS R US",
      "CNA",
      "EXCLUSIVE BOOKS",
      "BOOKS",
      "BOOKSTORE",
      "TYPO",
      "BOUTIQUE",
      "CLOTHING",
      "FASHION",
      "SHOES",
      "JEWEL*",
      "FURNITURE",
      "DECOR",
      "STORE",
      "STORES",
      "SHOP",
      "RETAIL",
      "MALL",
      "PLAZA",
    ],
  },

  // --- Cash ---
  { category: "cash", confidence: 0.9, keywords: ["ATM", "CASH WITHDRAWAL", "CASH WITHDRAWL", "WITHDRAWAL", "CASHSEND", "CASH SEND", "EWALLET", "E WALLET", "CASH BACK", "CASHBACK"] },

  // --- Transfers & EFTs (generic; kept last so a descriptive EFT like
  //     "PAYMENT TO SUNSET APARTMENTS RENT" is caught by rent above) ---
  {
    category: "transfers",
    confidence: 0.75,
    keywords: [
      "TRANSFER*",
      "TRF",
      "TFR",
      "OWN ACCOUNT",
      "OWN ACC",
      "INTERNAL",
      "INTER ACCOUNT",
      "INTER ACC",
      "IB TRANSFER",
      "IB PAYMENT",
      "INTERNET BANKING",
      "ONLINE BANKING",
      "FASTER PAYMENT",
      "FASTER PAY",
      "IMMEDIATE PAYMENT",
      "RTC",
      "EFT",
      "PAYMENT TO",
      "PAYMENT FROM",
      "PMT TO",
      "PMT FROM",
      "PAYSHAP",
      "PAY SHAP",
      "SAVINGS",
      "SAVE",
      "INVEST*",
      "EASY EQUITIES",
      "EASYEQUITIES",
      "SATRIX",
      "ALLAN GRAY",
      "CORONATION",
      "TYME",
      "CAPITEC",
      "FNB",
      "ABSA",
      "NEDBANK",
      "STANDARD BANK",
      "INVESTEC",
      "SNAPSCAN",
      "ZAPPER",
      "PAYPAL",
      "PAYFAST",
      "YOCO",
      "OZOW",
      "STITCH",
    ],
  },
];

export type MccRule = { from: number; to: number; category: Category; label: string };

/**
 * Merchant Category Code ranges (ISO 18245). Only consulted when Investec
 * supplies an `mcc` on the transaction AND no keyword rule matched.
 */
export const MCC_RULES: MccRule[] = [
  { from: 5411, to: 5411, category: "groceries", label: "grocery stores & supermarkets" },
  { from: 5422, to: 5499, category: "groceries", label: "food stores (butchers, bakeries, markets)" },
  { from: 5811, to: 5814, category: "eating_out", label: "restaurants & fast food" },
  { from: 5541, to: 5542, category: "transport_fuel", label: "service & fuel stations" },
  { from: 5983, to: 5983, category: "transport_fuel", label: "fuel dealers" },
  { from: 4111, to: 4131, category: "transport_fuel", label: "commuter transport, taxis & buses" },
  { from: 4511, to: 4511, category: "transport_fuel", label: "airlines" },
  { from: 4784, to: 4784, category: "transport_fuel", label: "tolls & bridge fees" },
  { from: 7523, to: 7523, category: "transport_fuel", label: "parking" },
  { from: 4900, to: 4900, category: "utilities", label: "utilities (electricity, water, gas)" },
  { from: 4812, to: 4816, category: "telecom", label: "telecommunications" },
  { from: 4899, to: 4899, category: "subscriptions", label: "cable & streaming services" },
  { from: 5968, to: 5968, category: "subscriptions", label: "continuity / subscription merchants" },
  { from: 7997, to: 7997, category: "subscriptions", label: "membership clubs & gyms" },
  { from: 6300, to: 6300, category: "insurance", label: "insurance" },
  { from: 6381, to: 6381, category: "insurance", label: "insurance premiums" },
  { from: 6513, to: 6513, category: "rent_housing", label: "real estate agents & rentals" },
  { from: 5912, to: 5912, category: "health", label: "pharmacies" },
  { from: 8011, to: 8099, category: "health", label: "medical & health services" },
  { from: 7832, to: 7841, category: "entertainment", label: "cinemas & video" },
  { from: 7911, to: 7999, category: "entertainment", label: "entertainment & recreation" },
  { from: 5735, to: 5735, category: "entertainment", label: "record & music stores" },
  { from: 6010, to: 6011, category: "cash", label: "cash disbursement / ATM" },
  { from: 5200, to: 5399, category: "shopping", label: "home, hardware & general merchandise" },
  { from: 5611, to: 5699, category: "shopping", label: "clothing & apparel" },
  { from: 5712, to: 5734, category: "shopping", label: "furniture, appliances & electronics" },
  { from: 5940, to: 5949, category: "shopping", label: "hobby, sporting & speciality retail" },
  { from: 5970, to: 5999, category: "shopping", label: "miscellaneous retail" },
];

export function lookupMcc(mcc: string | null | undefined): MccRule | null {
  if (!mcc) return null;
  const code = Number.parseInt(mcc, 10);
  if (!Number.isFinite(code)) return null;
  for (const rule of MCC_RULES) {
    if (code >= rule.from && code <= rule.to) return rule;
  }
  return null;
}
